spring:
  datasource:
    url: jdbc:mysql://localhost/softstore
    username: ben
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379

